/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.programacion.gui;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author eliseo_lopezp
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelSidebar = new javax.swing.JPanel();
        btnGrafico = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnAlmacen = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btnMovimiento = new javax.swing.JButton();
        btnAcceso = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelContenido = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard - Sistema de Punto de Venta");
        setPreferredSize(new java.awt.Dimension(1400, 800));

        panelSidebar.setBackground(new java.awt.Color(37, 81, 85));
        panelSidebar.setPreferredSize(new java.awt.Dimension(250, 800));
        panelSidebar.setLayout(new java.awt.GridBagLayout());

        btnGrafico.setBackground(new java.awt.Color(187, 153, 170));
        btnGrafico.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnGrafico.setText("Gráfico");
        btnGrafico.setBorderPainted(false);
        btnGrafico.setFocusPainted(false);
        btnGrafico.setOpaque(true);
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        panelSidebar.add(btnGrafico, gridBagConstraints);

        btnUsuario.setBackground(new java.awt.Color(187, 153, 170));
        btnUsuario.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.setBorderPainted(false);
        btnUsuario.setFocusPainted(false);
        btnUsuario.setOpaque(true);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelSidebar.add(btnUsuario, gridBagConstraints);

        btnAlmacen.setBackground(new java.awt.Color(187, 153, 170));
        btnAlmacen.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnAlmacen.setText("Almacén");
        btnAlmacen.setBorderPainted(false);
        btnAlmacen.setFocusPainted(false);
        btnAlmacen.setOpaque(true);
        btnAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelSidebar.add(btnAlmacen, gridBagConstraints);

        btnVenta.setBackground(new java.awt.Color(187, 153, 170));
        btnVenta.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnVenta.setText("Venta");
        btnVenta.setBorderPainted(false);
        btnVenta.setFocusPainted(false);
        btnVenta.setOpaque(true);
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelSidebar.add(btnVenta, gridBagConstraints);

        btnMovimiento.setBackground(new java.awt.Color(187, 153, 170));
        btnMovimiento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnMovimiento.setText("Movimiento");
        btnMovimiento.setBorderPainted(false);
        btnMovimiento.setFocusPainted(false);
        btnMovimiento.setOpaque(true);
        btnMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelSidebar.add(btnMovimiento, gridBagConstraints);

        btnAcceso.setBackground(new java.awt.Color(187, 153, 170));
        btnAcceso.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnAcceso.setText("Acceso");
        btnAcceso.setBorderPainted(false);
        btnAcceso.setFocusPainted(false);
        btnAcceso.setOpaque(true);
        btnAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelSidebar.add(btnAcceso, gridBagConstraints);

        btnInfo.setBackground(new java.awt.Color(187, 153, 170));
        btnInfo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnInfo.setText("Acerca de");
        btnInfo.setBorderPainted(false);
        btnInfo.setFocusPainted(false);
        btnInfo.setOpaque(true);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelSidebar.add(btnInfo, gridBagConstraints);

        btnSalir.setBackground(new java.awt.Color(204, 68, 85));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusPainted(false);
        btnSalir.setOpaque(true);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 10, 10);
        panelSidebar.add(btnSalir, gridBagConstraints);

        panelContenido.setBackground(new java.awt.Color(96, 173, 238));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelContenido))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContenido)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
        JOptionPane.showMessageDialog(this, "Funcionalidad de Gráfico en desarrollo", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGraficoActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        try {
            System.out.println("Creando frmUsuario...");
            frmUsuario usuario = new frmUsuario();
            System.out.println("frmUsuario creado exitosamente");
            abrirFormulario(usuario);
        } catch (Exception e) {
            System.err.println("Error al crear frmUsuario: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al abrir formulario de Usuario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenActionPerformed
        try {
            System.out.println("Creando frmProducto...");
            frmProducto producto = new frmProducto();
            System.out.println("frmProducto creado exitosamente");
            abrirFormulario(producto);
        } catch (Exception e) {
            System.err.println("Error al crear frmProducto: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al abrir formulario de Producto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAlmacenActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        abrirFormulario(new frmVenta());
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientoActionPerformed
        abrirFormulario(new frmMovimiento());
    }//GEN-LAST:event_btnMovimientoActionPerformed

    private void btnAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoActionPerformed
        JOptionPane.showMessageDialog(this, "Funcionalidad de Acceso en desarrollo", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAccesoActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        JOptionPane.showMessageDialog(this, "Sistema de Punto de Venta v1.0\\nDesarrollado con NetBeans", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?", "Confirmar Salida", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void abrirFormulario(JInternalFrame formulario) {
        try {
            System.out.println("Intentando abrir formulario: " + formulario.getClass().getSimpleName());
            
            // Cerrar formularios abiertos previamente del mismo tipo
            for (JInternalFrame frame : panelContenido.getAllFrames()) {
                if (frame.getClass().equals(formulario.getClass())) {
                    frame.dispose();
                }
            }
            
            // Agregar el formulario al panel de contenido
            panelContenido.add(formulario);
            formulario.setVisible(true);
            
            // Intentar maximizar
            try {
                formulario.setMaximum(true);
                System.out.println("Formulario maximizado correctamente");
            } catch (java.beans.PropertyVetoException e) {
                logger.warning("No se pudo maximizar el formulario: " + e.getMessage());
                System.out.println("Error al maximizar: " + e.getMessage());
            }
            
            // Traer al frente
            formulario.toFront();
            formulario.setSelected(true);
            
            System.out.println("Formulario abierto exitosamente");
            
        } catch (Exception e) {
            System.err.println("Error al abrir formulario: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceso;
    private javax.swing.JButton btnAlmacen;
    private javax.swing.JButton btnGrafico;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnMovimiento;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVenta;
    private javax.swing.JDesktopPane panelContenido;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}